spring.application.name=SmartBase

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_base
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

server.port=8081

jwt.secret=${SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER_NAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logger
logging.level.root=info
logging.level.io.swagger.models.parameters.AbstractSerializableParameter=ERROR
logging.level.greencity.exception.handler.CustomExceptionHandler=trace
logging.pattern.console=%d{"yyyy/MM/dd HH:mm:ss,SSS"} %magenta([%thread]) %highlight(%-5level) %M\\(%F:%L\\) - %msg%n

azure.storage.connection-string=${AZURE_BLOB}
azure.storage.container-name=images


