spring.application.name=SmartBase

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_base
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

server.port=8081

