INSERT INTO technologies (name)
VALUES
    ('Java'),
    ('Spring Boot'),
    ('Hibernate'),
    ('JavaScript'),
    ('React'),
    ('Angular'),
    ('Node.js'),
    ('Vue.js'),
    ('Python'),
    ('Django'),
    ('Flask'),
    ('Ruby on Rails'),
    ('PHP'),
    ('Laravel'),
    ('MySQL'),
    ('PostgreSQL'),
    ('MongoDB'),
    ('Redis'),
    ('Docker'),
    ('Kubernetes'),
    ('AWS'),
    ('Google Cloud Platform'),
    ('Azure'),
    ('.NET'),
    ('ASP.NET'),
    ('Entity Framework'),
    ('Apache Hadoop'),
    ('Apache Spark'),
    ('Kafka'),
    ('Python Pandas'),
    ('Python NumPy'),
    ('NLP'),
    ('Airflow'),
    ('Tableau'),
    ('Power BI')
ON CONFLICT (name) DO NOTHING;